### ISSUE TITLE
i make ports can i join this

### ISSUE THREAD

**Issue by fnfporterhi** [TeamPorters/.github#1]
title <3

**Comment by LEVIXDDLMAO** [comment]
this was ment for me and hoovy and sanco since we been friends for awhile now

**Comment by fnfporterhi** [comment]
oof sorry 😭

**Comment by SanicBTW** [comment]
that went deep 💔

**Comment by fnfporterhi** [comment]
same bro 💔

**Comment by LEVIXDDLMAO** [comment]
wait what?

**Comment by LEVIXDDLMAO** [comment]
> this was ment for me and hoovy and sanco since we been friends for awhile now

order is wrong- it was me and sanco first and dom and then hoovy

**Comment by SanicBTW** [comment]
my guy :Skull:

**Comment by LEVIXDDLMAO** [comment]
ack i dont know-

**Comment by SanicBTW** [comment]
team is more dead than me bro wtf

**Comment by LEVIXDDLMAO** [comment]
i been busy 🙁
________________________________

**Comment by fnfporterhi** [comment]
so been i
